from DMT.GameData import DataManager
from commandNLP.nlp import nlp
import unittest

dm = DataManager()
dm.loadNewGame()
nlp = nlp()
nlp.loadProperties(dm.getVerbs(), dm.getPrepositions(), dm.getObjects(), dm.getVerbPrepositionCombos(), dm.getExits(), dm.getCommandTuples())

class Game(unittest.TestCase):

    data = [
            #{"input":"attack blinky",                 "target":"attack blinky"},
            #{"input":"attack clyde",                  "target":"attack clyde"},
            #{"input":"attack pinky",                  "target":"attack pinky"},
            #{"input":"attack inky",                   "target":"attack inky"}, 
            {"input":"drink bottle of gatorade",      "target":"drink bottle of gatorade"},
            {"input":"drink bottle of water",         "target":"drink bottle of water"},
            {"input":"drop armor",                    "target":"drop armor"},
            {"input":"drop axe",                      "target":"drop axe"},
            {"input":"drop book of locks",            "target":"drop book of locks"},
            {"input":"drop book of spells",           "target":"drop book of spells"},
            {"input":"drop bottle of gatorade",       "target":"drop bottle of gatorade"},
            {"input":"drop bottle of water",          "target":"drop bottle of water"},
            {"input":"drop bottleopener",             "target":"drop bottleopener"},
            {"input":"drop brass lantern",            "target":"drop brass lantern"},
            {"input":"drop broken lantern",           "target":"drop broken lantern"},
            {"input":"drop cloak",                    "target":"drop cloak"},
            {"input":"drop earthenware",              "target":"drop earthenware"},
            {"input":"drop fine china",               "target":"drop fine china"},
            {"input":"drop gem",                      "target":"drop gem"},
            {"input":"drop golden key",               "target":"drop golden key"},
            {"input":"drop green apple",              "target":"drop green apple"},
            {"input":"drop helmet",                   "target":"drop helmet"},
            {"input":"drop kitchen knife",            "target":"drop kitchen knife"},
            {"input":"drop lockpick",                 "target":"drop lockpick"},
            {"input":"drop machete",                  "target":"drop machete"},
            {"input":"drop magical ring",             "target":"drop magical ring"},
            {"input":"drop matches",                  "target":"drop matches"},
            {"input":"drop mushrooms",                "target":"drop mushrooms"},
            {"input":"drop note",                     "target":"drop note"},
            {"input":"drop red apple",                "target":"drop red apple"},
            {"input":"drop sabre",                    "target":"drop sabre"},
            {"input":"drop scroll",                   "target":"drop scroll"},
            {"input":"drop shale rocks",              "target":"drop shale rocks"},
            {"input":"drop slate rocks",              "target":"drop slate rocks"},
            {"input":"drop stoneware",                "target":"drop stoneware"},
            {"input":"drop treasure",                 "target":"drop treasure"},
            {"input":"drop warhammer",                "target":"drop warhammer"},
            {"input":"eat green apple",               "target":"eat green apple"},
            {"input":"eat mushrooms",                 "target":"eat mushrooms"},
            {"input":"eat red apple",                 "target":"eat red apple"},
            {"input":"equip armor",                   "target":"equip armor"},
            {"input":"equip axe",                     "target":"equip axe"},
            {"input":"equip cloak",                   "target":"equip cloak"},
            {"input":"equip helmet",                  "target":"equip helmet"},
            {"input":"equip kitchen knife",           "target":"equip kitchen knife"},
            {"input":"equip machete",                 "target":"equip machete"},
            {"input":"equip magical ring",            "target":"equip magical ring"},
            {"input":"equip sabre",                   "target":"equip sabre"},
            {"input":"equip warhammer",               "target":"equip warhammer"},
            {"input":"go west",                       "target":"go west"},
            {"input":"go east",                       "target":"go east"},
            {"input":"go south",                      "target":"go south"},
            {"input":"go north",                      "target":"go north"},
            {"input":"west",                          "target":"west"},
            {"input":"east",                          "target":"east"},
            {"input":"south",                         "target":"south"},
            {"input":"north",                         "target":"north"},
            {"input":"go bell archway",               "target":"go bell archway"},
            {"input":"go corrugated steel door",      "target":"go corrugated steel door"},
            {"input":"go creaking cell door",         "target":"go creaking cell door"},
            {"input":"go long dark tunnel",           "target":"go long dark tunnel"},
            {"input":"go monstrous archway",          "target":"go monstrous archway"},
            {"input":"go oblivion gate",              "target":"go oblivion gate"},
            {"input":"go old wooden door",            "target":"go old wooden door"},
            {"input":"go rolling shutter door",       "target":"go rolling shutter door"},
            {"input":"go rusted spiral staircase",    "target":"go rusted spiral staircase"},
            {"input":"go rusting iron door",          "target":"go rusting iron door"},
            {"input":"go smoky glazed doors",         "target":"go smoky glazed doors"},
            {"input":"go solid metal door",           "target":"go solid metal door"},
            {"input":"go splintered double doors",    "target":"go splintered double doors"},
            {"input":"go swinging door",              "target":"go swinging door"},
            {"input":"go winder stairs",              "target":"go winder stairs"},
            {"input":"bell archway",                  "target":"bell archway"},
            {"input":"corrugated steel door",         "target":"corrugated steel door"},
            {"input":"creaking cell door",            "target":"creaking cell door"},
            {"input":"long dark tunnel",              "target":"long dark tunnel"},
            {"input":"monstrous archway",             "target":"monstrous archway"},
            {"input":"oblivion gate",                 "target":"oblivion gate"},
            {"input":"old wooden door",               "target":"old wooden door"},
            {"input":"rolling shutter door",          "target":"rolling shutter door"},
            {"input":"rusted spiral staircase",       "target":"rusted spiral staircase"},
            {"input":"rusting iron door",             "target":"rusting iron door"},
            {"input":"smoky glazed doors",            "target":"smoky glazed doors"},
            {"input":"solid metal door",              "target":"solid metal door"},
            {"input":"splintered double doors",       "target":"splintered double doors"},
            {"input":"swinging door",                 "target":"swinging door"},
            {"input":"winder stairs",                 "target":"winder stairs"},
            #{"input":"savegame",                      "target":"savegame"},
            #{"input":"loadgame",                      "target":"loadgame"},
            #{"input":"help",                          "target":"help"},
            #{"input":"ghosts",                        "target":"ghosts"},
            #{"input":"inventory",                     "target":"inventory"},
            {"input":"lay on altar",                  "target":"lay on altar"},
            {"input":"lay on bearskin",               "target":"lay on bearskin"},
            {"input":"lay on bunk bed",               "target":"lay on bunk bed"},
            {"input":"lay on mattress",               "target":"lay on mattress"},
            {"input":"lay on turkish rug",            "target":"lay on turkish rug"},
            {"input":"lay on twin bed",               "target":"lay on twin bed"},
            {"input":"lay on wool rug",               "target":"lay on wool rug"},
            {"input":"light brass lantern",           "target":"light brass lantern"},
            {"input":"look",                          "target":"look"},
            {"input":"look at altar",                 "target":"look at altar"},
            {"input":"look at armoire",               "target":"look at armoire"},
            {"input":"look at armor",                 "target":"look at armor"},
            {"input":"look at axe",                   "target":"look at axe"},
            {"input":"look at bar stool",             "target":"look at bar stool"},
            {"input":"look at bat skeleton",          "target":"look at bat skeleton"},
            {"input":"look at bearskin",              "target":"look at bearskin"},
            {"input":"look at book of locks",         "target":"look at book of locks"},
            {"input":"look at book of spells",        "target":"look at book of spells"},
            {"input":"look at bottle of gatorade",    "target":"look at bottle of gatorade"},
            {"input":"look at bottle of water",       "target":"look at bottle of water"},
            {"input":"look at bottleopener",          "target":"look at bottleopener"},
            {"input":"look at brass lantern",         "target":"look at brass lantern"},
            {"input":"look at broken lantern",        "target":"look at broken lantern"},
            {"input":"look at bunk bed",              "target":"look at bunk bed"},
            {"input":"look at carver chair",          "target":"look at carver chair"},
            {"input":"look at cat skeleton",          "target":"look at cat skeleton"},
            {"input":"look at cedar trunk",           "target":"look at cedar trunk"},
            {"input":"look at chandelier",            "target":"look at chandelier"},
            {"input":"look at cloak",                 "target":"look at cloak"},
            {"input":"look at cooking hearth",        "target":"look at cooking hearth"},
            {"input":"look at corner shelves",        "target":"look at corner shelves"},
            {"input":"look at desk",                  "target":"look at desk"},
            {"input":"look at dining table",          "target":"look at dining table"},
            {"input":"look at earthenware",           "target":"look at earthenware"},
            {"input":"look at fine china",            "target":"look at fine china"},
            {"input":"look at gateleg table",         "target":"look at gateleg table"},
            {"input":"look at gem",                   "target":"look at gem"},
            {"input":"look at golden key",            "target":"look at golden key"},
            {"input":"look at green apple",           "target":"look at green apple"},
            {"input":"look at helmet",                "target":"look at helmet"},
            {"input":"look at high table",            "target":"look at high table"},
            {"input":"look at human skeleton",        "target":"look at human skeleton"},
            {"input":"look at iron lever",            "target":"look at iron lever"},
            {"input":"look at iron trunk",            "target":"look at iron trunk"},
            {"input":"look at key rung",              "target":"look at key rung"},
            {"input":"look at kitchen knife",         "target":"look at kitchen knife"},
            {"input":"look at kitchen table",         "target":"look at kitchen table"},
            {"input":"look at lidless eye",           "target":"look at lidless eye"},
            {"input":"look at lockpick",              "target":"look at lockpick"},
            {"input":"look at machete",               "target":"look at machete"},
            {"input":"look at magical ring",          "target":"look at magical ring"},
            {"input":"look at matches",               "target":"look at matches"},
            {"input":"look at mattress",              "target":"look at mattress"},
            {"input":"look at metal shelves",         "target":"look at metal shelves"},
            {"input":"look at milking stool",         "target":"look at milking stool"},
            {"input":"look at mushrooms",             "target":"look at mushrooms"},
            {"input":"look at note",                  "target":"look at note"},
            {"input":"look at painting",              "target":"look at painting"},
            {"input":"look at portrait",              "target":"look at portrait"},
            {"input":"look at red apple",             "target":"look at red apple"},
            {"input":"look at rocking chair",         "target":"look at rocking chair"},
            {"input":"look at round table",           "target":"look at round table"},
            {"input":"look at sabre",                 "target":"look at sabre"},
            {"input":"look at safe",                  "target":"look at safe"},
            {"input":"look at scroll",                "target":"look at scroll"},
            {"input":"look at shale rocks",           "target":"look at shale rocks"},
            {"input":"look at sign",                  "target":"look at sign"},
            {"input":"look at slate of runes",        "target":"look at slate of runes"},
            {"input":"look at slate rocks",           "target":"look at slate rocks"},
            {"input":"look at stoneware",             "target":"look at stoneware"},
            {"input":"look at tapestries",            "target":"look at tapestries"},
            {"input":"look at tools",                 "target":"look at tools"},
            {"input":"look at trapdoor",              "target":"look at trapdoor"},
            {"input":"look at treasure",              "target":"look at treasure"},
            {"input":"look at tree",                  "target":"look at tree"},
            {"input":"look at trestle table",         "target":"look at trestle table"},
            {"input":"look at turkish rug",           "target":"look at turkish rug"},
            {"input":"look at twin bed",              "target":"look at twin bed"},
            {"input":"look at wall of flames",        "target":"look at wall of flames"},
            {"input":"look at warhammer",             "target":"look at warhammer"},
            #{"input":"look at blinky",                "target":"look at blinky"},
            #{"input":"look at clyde",                 "target":"look at clyde"},
            #{"input":"look at pinky",                 "target":"look at pinky"},
            #{"input":"look at inky",                  "target":"look at inky"},
            {"input":"look at wooden lever",          "target":"look at wooden lever"},
            {"input":"look at wooden shelves",        "target":"look at wooden shelves"},
            {"input":"look at wool rug",              "target":"look at wool rug"},
            {"input":"look behind portrait",          "target":"look behind portrait"},
            {"input":"look behind wooden shelves",    "target":"look behind wooden shelves"},
            {"input":"look inside armoire",           "target":"look into armoire"},
            {"input":"look inside cedar trunk",       "target":"look into cedar trunk"},
            {"input":"look inside desk",              "target":"look into desk"},
            {"input":"look inside iron trunk",        "target":"look into iron trunk"},
            {"input":"look inside safe",              "target":"look into safe"},
            {"input":"look into armoire",             "target":"look into armoire"},
            {"input":"look into cedar trunk",         "target":"look into cedar trunk"},
            {"input":"look into desk",                "target":"look into desk"},
            {"input":"look into iron trunk",          "target":"look into iron trunk"},
            {"input":"look into safe",                "target":"look into safe"},
            {"input":"look on altar",                 "target":"look on altar"},
            {"input":"look on corner shelves",        "target":"look on corner shelves"},
            {"input":"look on desk",                  "target":"look on desk"},
            {"input":"look on dining table",          "target":"look on dining table"},
            {"input":"look on gateleg table",         "target":"look on gateleg table"},
            {"input":"look on high table",            "target":"look on high table"},
            {"input":"look on kitchen table",         "target":"look on kitchen table"},
            {"input":"look on mattress",              "target":"look on mattress"},
            {"input":"look on metal shelves",         "target":"look on metal shelves"},
            {"input":"look on round table",           "target":"look on round table"},
            {"input":"look on trestle table",         "target":"look on trestle table"},
            {"input":"look on wooden shelves",        "target":"look on wooden shelves"},
            {"input":"look under bearskin",           "target":"look under bearskin"},
            {"input":"look under bunk bed",           "target":"look under bunk bed"},
            {"input":"look under mattress",           "target":"look under mattress"},
            {"input":"look under turkish rug",        "target":"look under turkish rug"},
            {"input":"look under wool rug",           "target":"look under wool rug"},
            {"input":"pull wooden lever",             "target":"pull wooden lever"},
            {"input":"pull trapdoor",                 "target":"pull trapdoor"},
            {"input":"push iron lever",               "target":"push iron lever"},
            {"input":"read book of locks",            "target":"read book of locks"},
            {"input":"read book of spells",           "target":"read book of spells"},
            {"input":"read note",                     "target":"read note"},
            {"input":"read scroll",                   "target":"read scroll"},
            {"input":"read sign",                     "target":"read sign"},
            {"input":"read slate of runes",           "target":"read slate of runes"},
            {"input":"sit on bar stool",              "target":"sit on bar stool"},
            {"input":"sit on bunk bed",               "target":"sit on bunk bed"},
            {"input":"sit on carver chair",           "target":"sit on carver chair"},
            {"input":"sit on milking stool",          "target":"sit on milking stool"},
            {"input":"sit on rocking chair",          "target":"sit on rocking chair"},
            {"input":"sit on twin bed",               "target":"sit on twin bed"},
            {"input":"take armor",                    "target":"take armor"},
            {"input":"take axe",                      "target":"take axe"},
            {"input":"take book of locks",            "target":"take book of locks"},
            {"input":"take book of spells",           "target":"take book of spells"},
            {"input":"take bottle of gatorade",       "target":"take bottle of gatorade"},
            {"input":"take bottle of water",          "target":"take bottle of water"},
            {"input":"take bottleopener",             "target":"take bottleopener"},
            {"input":"take brass lantern",            "target":"take brass lantern"},
            {"input":"take broken lantern",           "target":"take broken lantern"},
            {"input":"take cloak",                    "target":"take cloak"},
            {"input":"take earthenware",              "target":"take earthenware"},
            {"input":"take fine china",               "target":"take fine china"},
            {"input":"take gem",                      "target":"take gem"},
            {"input":"take golden key",               "target":"take golden key"},
            {"input":"take green apple",              "target":"take green apple"},
            {"input":"take helmet",                   "target":"take helmet"},
            {"input":"take kitchen knife",            "target":"take kitchen knife"},
            {"input":"take lockpick",                 "target":"take lockpick"},
            {"input":"take machete",                  "target":"take machete"},
            {"input":"take magical ring",             "target":"take magical ring"},
            {"input":"take matches",                  "target":"take matches"},
            {"input":"take mushrooms",                "target":"take mushrooms"},
            {"input":"take note",                     "target":"take note"},
            {"input":"take red apple",                "target":"take red apple"},
            {"input":"take sabre",                    "target":"take sabre"},
            {"input":"take scroll",                   "target":"take scroll"},
            {"input":"take shale rocks",              "target":"take shale rocks"},
            {"input":"take slate rocks",              "target":"take slate rocks"},
            {"input":"take stoneware",                "target":"take stoneware"},
            {"input":"take treasure",                 "target":"take treasure"},
            {"input":"take warhammer",                "target":"take warhammer"},
            {"input":"unequip armor",                 "target":"unequip armor"},
            {"input":"unequip axe",                   "target":"unequip axe"},
            {"input":"unequip cloak",                 "target":"unequip cloak"},
            {"input":"unequip helmet",                "target":"unequip helmet"},
            {"input":"unequip kitchen knife",         "target":"unequip kitchen knife"},
            {"input":"unequip machete",               "target":"unequip machete"},
            {"input":"unequip magical ring",          "target":"unequip magical ring"},
            {"input":"unequip sabre",                 "target":"unequip sabre"},
            {"input":"unequip warhammer",             "target":"unequip warhammer"},
            {"input":"unlock west",                   "target":"unlock west"},
            {"input":"unlock east",                   "target":"unlock east"},
            {"input":"unlock north",                  "target":"unlock north"},
            {"input":"unlock south",                  "target":"unlock south"},
            {"input":"unlock iron trunk",             "target":"unlock iron trunk"},
            {"input":"unlock safe",                   "target":"unlock safe"},
            {"input":"unlock corrugated steel door",  "target":"unlock corrugated steel door"} ]
   
   
    def test_NLP_mapping(self):
        for i in self.data:
            self.assertEqual(nlp.buildTuple(i['input']), i['target'])
           


    
    
if __name__ == '__main__':
	unittest.main()
